# Generated by Django 4.2.3 on 2023-07-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floor_number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Elevator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_floors", models.IntegerField()),
                ("current_floor", models.IntegerField(default=1)),
                ("direction", models.CharField(default="STOPPED", max_length=10)),
                ("door_open", models.BooleanField(default=False)),
                ("is_running", models.BooleanField(default=False)),
                ("is_available", models.BooleanField(default=True)),
                ("is_operational", models.BooleanField(default=True)),
                (
                    "destinations",
                    models.ManyToManyField(blank=True, to="elevator.floor"),
                ),
            ],
        ),
    ]
